// Please only edit the config with the command /set
l1x: 0
l1y: 0
l1z: 0
l2x: 0
l2y: 0
l2z: 0
g1x: 0
g1y: 0
g1z: 0
g2x: 0
g2y: 0
g2z: 0
g3x: 0
g3y: 0 
g3z: 0
g4x: 0
g4y: 0
g4z: 0
spawnx: 0
spawny: 0
spawnz: 0
igx: 0
igy: 0
igz: 0
shutdown: false